sudo: required 
language: generic

services:
  - docker 

before_install: 
  - docker build -t christianlehre/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true christianlehre/docker-react npm run test

