version: '3'
services: 
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules # do not try to map between container and local machine (no colon)
      - .:/app # current dir in local machine mapp to /app inside the container
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # placeholder, do not want to override
      - .:/app 
    command: ["npm", "run", "test"] # override Startup command of the container
  


